### PR TITLE
Made some styling changes and logical changes.

### PR DESCRIPTION
**Pull request by Abhiramborige**
Dark mode redesigned
Made a button to roll the dice
Cannot again roll the dice while it is rolling
Able to Roll again after the previous roll completes and stops.

### CODE REVIEW

**Comment by Abhiramborige** [comment]
image

**Comment by Abhiramborige** [comment]
image

**Comment by anasvakyathodi** [comment]
@Abhiramborige  Thanks for your contribution :)

**Comment by Abhiramborige** [comment]
Thankyou !!!

**Pull request merged**
